### ISSUE TITLE
PWA Setups

### ISSUE THREAD

**Issue by ellisajung** [Coopang/ai-search-engine#21]
### Task Description

Tasks related to PWA configuration and setup.

### Task List

- [x] Make the app installable - add manifest file, service worker, icons, splash screens etc.
- [ ] Customize the default browser installation prompts
- [ ] Make a custom installation button/interface

### Relevant Links/References

.
